import botSadLogo from 'src/app/assets/images/bot-sad-logo.png';
import s from './footer.module.scss';
import classNames from 'classnames';

export const Footer = () => (
    <footer
        className={s['footer']}
    >
        <div
            className={s['info']}
        >
            <img
                src={botSadLogo}
                alt={'Бот сад'}
                className={s['logo']}
            />
            <p>
                Рекламно<br/>
                производственная<br/>
                компания
            </p>
            <div
                className={s['activity']}
            >
                <p
                    className={s['activity-p']}
                >
                    Режим работы
                </p>
                <ul
                    className={s['activity-list']}
                >
                    <li>
                        пн-пт:09.00-18.00
                    </li>
                    <li>
                        сб: 10.00-13.00
                    </li>
                    <li>
                        вс: выходной
                    </li>
                </ul>
            </div>
        </div>
        <div
            className={s['nav-wrapper']}
        >
            <div
                className={s['nav']}
            >
                <ul
                    className={s['nav-list']}
                >
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/'}
                        >
                            Главная
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/company/'}
                        >
                            О нас
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/contacts/'}
                        >
                            Контакты
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/projects/'}
                        >
                            Проекты
                        </a>
                    </li>
                    <li
                        className={classNames(s['list-item'], s['sub-item'])}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/services/'}
                        >
                            Услуги
                        </a>
                        <ul
                            className={s['sub-list']}
                        >
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/outdoor-advertising/'}
                                >
                                    Наружная реклама
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/polygraphy/'}
                                >
                                    Полиграфия
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/mobile-constructions/'}
                                >
                                    Мобильные конструкции
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/souvenirs/'}
                                >
                                    Сувениры
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/interior-print/'}
                                >
                                    Стенды, таблички, уголки покупателей
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/car-branding/'}
                                >
                                    Брендирование автомобилей
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/custom-products/'}
                                >
                                    Нестандартные изделия
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                    href={'https://bot-sad.com/services/design/'}
                                >
                                    Дизайн и техдизайн
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/blog/'}
                        >
                            Блог
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/portfolio/'}
                        >
                            Портфолио
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                            href={'https://bot-sad.com/for-property-developers/'}
                        >
                            Застройщикам
                        </a>
                    </li>
                </ul>
            </div>
            <div
                className={s['links']}
            >
                <a
                    href={'https://bot-sad.com/upload/iblock/65e/alixperdsn5rwow0fnnzv4ngvdy1e1eu/%D0%BF%D1%80%D0%B0%D0%B9%D1%81%2005.10.2023.pdf'}
                >
                    Прайс лист
                </a>
                <a
                    href={'https://bot-sad.com/upload/iblock/544/min3x17ql052c5974zbo3vt7mixg4c12/%D0%A2%D0%95%D0%A5.%20%D0%A2%D0%A0%D0%95%D0%91%D0%9E%D0%92%D0%90%D0%9D%D0%98%D0%AF.pdf'}
                >
                    Тех. требования к макетам
                </a>
            </div>
            <div
                className={s['address']}
            >
                <ul
                    className={s['address-list']}
                >
                    <li
                        className={s['item']}
                    >
                        адрес: г. Хабаровск, ул. Доватора 5/0
                    </li>
                    <li
                        className={s['item']}
                    >
                        телефон:
                        <a
                            href={'tel:+74212707000'}
                        >
                            +7 (4212) 707-000
                        </a>
                    </li>
                </ul>
                <ul
                    className={s['address-list']}
                >
                    <li
                        className={s['item']}
                    >
                        почта:
                        <a
                            href={'mailto:mail@bot-sad.com'}
                        >
                            mail@bot-sad.com
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
);
