import botSadLogo from 'src/app/assets/images/bot-sad-logo.png';
import s from './footer.module.scss';
import classNames from 'classnames';

export const Footer = () => (
    <footer
        className={s['footer']}
    >
        <div
            className={s['info']}
        >
            <img
                src={botSadLogo}
                alt={'Бот сад'}
                className={s['logo']}
            />
            <p>
                Рекламно<br/>
                производственная<br/>
                компания
            </p>
            <div
                className={s['activity']}
            >
                <p
                    className={s['activity-p']}
                >
                    Режим работы
                </p>
                <ul
                    className={s['activity-list']}
                >
                    <li>
                        пн-пт:09.00-18.00
                    </li>
                    <li>
                        сб: 10.00-13.00
                    </li>
                    <li>
                        вс: выходной
                    </li>
                </ul>
            </div>
        </div>
        <div
            className={s['nav-wrapper']}
        >
            <div
                className={s['nav']}
            >
                <ul
                    className={s['nav-list']}
                >
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                        >
                            Главная
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                        >
                            О нас
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                        >
                            Контакты
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                        >
                            Проекты
                        </a>
                    </li>
                    <li
                        className={classNames(s['list-item'], s['sub-item'])}
                    >
                        <a
                            className={s['link']}
                        >
                            Услуги
                        </a>
                        <ul
                            className={s['sub-list']}
                        >
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Наружная реклама
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Полиграфия
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Мобильные конструкции
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Сувениры
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Стенды, таблички, уголки покупателей
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Брендирование автомобилей
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Нестандартные изделия
                                </a>
                            </li>
                            <li
                                className={s['list-item']}
                            >
                                <a
                                    className={s['link']}
                                >
                                    Дизайн и техдизайн
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                        >
                            Блог
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                        >
                            Портфолио
                        </a>
                    </li>
                    <li
                        className={s['list-item']}
                    >
                        <a
                            className={s['link']}
                        >
                            Застройщикам
                        </a>
                    </li>
                </ul>
            </div>
            <div
                className={s['links']}
            >
                <a>
                    Прайс лист
                </a>
                <a>
                    Тех. требования к макетам
                </a>
            </div>
            <div
                className={s['address']}
            >
                <ul
                    className={s['address-list']}
                >
                    <li
                        className={s['item']}
                    >
                        адрес: г. Хабаровск, ул. Доватора 5/0
                    </li>
                    <li
                        className={s['item']}
                    >
                        телефон:
                        <a
                            href={'tel:+74212707000'}
                        >
                            +7 (4212) 707-000
                        </a>
                    </li>
                </ul>
                <ul
                    className={s['address-list']}
                >
                    <li
                        className={s['item']}
                    >
                        почта:
                        <a
                            href={'mailto:mail@bot-sad.com'}
                        >
                            mail@bot-sad.com
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
);
